---
title: "proj651"
author: "Xin Luo"
date: "2022/4/11"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
setwd('C:/Users/luosa/OneDrive/Desktop/651/final')
```

```{r}
library(tidyverse)
library(gtable)
library(gtsummary)
library(gridExtra)
library(knitr)
library(car)
library(boot)
data <- readRDS("Dataset.RData")
```

```{r}
data$y = 0
data$y[data$survival == 'Long'] = 1
# immune selected genes MC1R, AKT1, NAMPT, TNFRSF19, PAK2, SOS1, B2M 
l1 <- glm(data$y ~ data$MC1R + as.factor(data$stage), family = 'binomial')
l1$coefficients[2]
l2 <- glm(data$y ~ data$AKT1 + as.factor(data$stage), family = 'binomial')
l2$coefficients[2]
l3 <- glm(data$y ~ data$NAMPT + as.factor(data$stage), family = 'binomial')
l3$coefficients[2]
l4 <- glm(data$y ~ data$TNFRSF19 + as.factor(data$stage), family = 'binomial')
l4$coefficients[2]
l5 <- glm(data$y ~ data$PAK2 + as.factor(data$stage), family = 'binomial')
l5$coefficients[2]
l6 <- glm(data$y ~ data$SOS1 + as.factor(data$stage), family = 'binomial')
l6$coefficients[2]
l7 <- glm(data$y ~ data$B2M + as.factor(data$stage), family = 'binomial')
l7$coefficients[2]
```

```{r}
dd = data[c('MC1R', 'AKT1', 'NAMPT', 'TNFRSF19', 'PAK2', 'SOS1', 'B2M')] 
library(plotly)
library(ggcorrplot)
library(heatmaply)
heatmaply_cor(cor(dd))
```

```{r}
cor(dd)
```

```{r}
dd1 = as.data.frame(dd)
dd1$y = data$y
dd1$age_c = data$age - mean(data$age)
dd1$sex = 0
dd1$sex[data$gender == 'female'] = 1
dd1$pathStage = as.factor(data$stage)
model = glm(y ~ MC1R + AKT1 + NAMPT + TNFRSF19 + PAK2 + SOS1 + B2M + pathStage, data = dd1, family = 'binomial')
vif(model)
```

```{r}
# selected top genes: MC1R, AKT1, PAK2, SOS1, B2M
# model 1: basline + selected top genes

model1 <- glm(y ~ MC1R + AKT1 + PAK2 + SOS1 + B2M + sex + age_c + pathStage, data = dd1, family = 'binomial')
summary(model1)
```
```{r residual diagnostics}
model1.diag <- glm.diag(model1)
data.frame("cooks" = model1.diag$cook, "leverage" = model1.diag$h) %>%
  pivot_longer(everything(), names_to = "measure") %>%
  mutate(cutoff = ifelse(measure=="cooks",1,26/240)) %>%
  ggplot(aes(x = seq(0.5,240,by=0.5))) +
  geom_line(aes(y = value, col = measure)) +
  geom_line(aes(y = cutoff), lty = 2, alpha = 0.5) +
  theme_classic() +
  facet_wrap(~measure, scales = "free_y", nrow = 2) +
  scale_color_manual(values = c("orange","cornflowerblue")) +
  labs(x = "observation")
```

```{r }
p_res1 <- residuals(model1, type = "pearson")
d_res1 <- residuals(model1, type = "deviance")
data.frame("pearson" = p_res1, "deviance" = d_res1) %>%
  pivot_longer(everything(), names_to = "residual") %>%
  ggplot(aes(x = seq(0.5,240,by=0.5), y = value, col = residual)) +
  geom_point() +
  facet_wrap(~residual, nrow = 2) +
  theme_classic() +
  scale_color_manual(values = c("darkgreen","purple")) +
  labs(x = "observation")
data.frame("pearson" = model1.diag$rp, "deviance" = model1.diag$rd) %>%
  pivot_longer(everything(), names_to = "residual") %>%
  ggplot(aes(x = seq(0.5,240,by=0.5), y = value, col = residual)) +
  geom_point() +
  facet_wrap(~residual, nrow = 2) +
  theme_classic() +
  scale_color_manual(values = c("darkgoldenrod2","orchid3")) +
  labs(x = "observation", y = "standardized values")
#kable(data.frame("pearson" = p_res1, "deviance" = d_res1,"leverage" = model1.diag$h, "cooks" = model1.diag$cook,"p_standard" = model1.diag$rp, "d_standard" = model1.diag$rd),col.names = c("$\\hat{r}^{P}$","$\\hat{r}^{D}$","leverage","cooks","$\\hat{r}^{PS}$","$\\hat{r}^{DS}$"))
```


```{r}
# model 2: baseline + selected top genes + immune resposne genes
dd1$CD86 = data$CD86
dd1$DDX58 = data$DDX58
dd1$KLRD1 = data$KLRD1
dd1$TLR4 = data$TLR4
dd1$DCK = data$DCK
dd1$C5 = data$C5
dd1$CCL28 = data$CCL28
dd1$RFX5 = data$RFX5
dd1$EIF2AK2 = data$EIF2AK2
model2 <- glm(y ~ MC1R + AKT1 + PAK2 + SOS1 + B2M + sex + age_c + CD86 + DDX58 + KLRD1 + TLR4 
              + C5 + CCL28 + RFX5 + EIF2AK2 + DCK + pathStage, data = dd1, family = 'binomial')
summary(model2)
```


```{r}
model2.diag <- glm.diag(model2)
data.frame("cooks" = model2.diag$cook, "leverage" = model2.diag$h) %>%
  pivot_longer(everything(), names_to = "measure") %>%
  mutate(cutoff = ifelse(measure=="cooks",1,26/240)) %>%
  ggplot(aes(x = seq(0.5,240,by=0.5))) +
  geom_line(aes(y = value, col = measure)) +
  geom_line(aes(y = cutoff), lty = 2, alpha = 0.5) +
  theme_classic() +
  facet_wrap(~measure, scales = "free_y", nrow = 2) +
  scale_color_manual(values = c("orange","cornflowerblue")) +
  labs(x = "observation")
```

```{r}
p_res2 <- residuals(model2, type = "pearson")
d_res2 <- residuals(model2, type = "deviance")
data.frame("pearson" = p_res2, "deviance" = d_res2) %>%
  pivot_longer(everything(), names_to = "residual") %>%
  ggplot(aes(x = seq(0.5,240,by=0.5), y = value, col = residual)) +
  geom_point() +
  facet_wrap(~residual, nrow = 2) +
  theme_classic() +
  scale_color_manual(values = c("darkgreen","purple")) +
  labs(x = "observation")
data.frame("pearson" = model2.diag$rp, "deviance" = model2.diag$rd) %>%
  pivot_longer(everything(), names_to = "residual") %>%
  ggplot(aes(x = seq(0.5,240,by=0.5), y = value, col = residual)) +
  geom_point() +
  facet_wrap(~residual, nrow = 2) +
  theme_classic() +
  scale_color_manual(values = c("darkgoldenrod2","orchid3")) +
  labs(x = "observation", y = "standardized values")
#kable(data.frame("pearson" = p_res2, "deviance" = d_res2,"leverage" = model2.diag$h, "cooks" = model2.diag$cook,"p_standard" = model2.diag$rp, "d_standard" = model2.diag$rd),col.names = c("$\\hat{r}^{P}$","$\\hat{r}^{D}$","leverage","cooks","$\\hat{r}^{PS}$","$\\hat{r}^{DS}$"))
```

```{r}
# model 3: baseline + selected top genes + immune response genes + age:immunse response genes
model3 <- glm(y ~ MC1R + AKT1 + PAK2 + SOS1 + B2M + sex + age_c + CD86 + DDX58 + KLRD1 + TLR4
                + age_c:CD86 + age_c:DDX58 + age_c:KLRD1 + age_c:TLR4 , data = dd1, family = 'binomial')
summary(model3)
```
```{r}
model3.diag <- glm.diag(model3)
data.frame("cooks" = model3.diag$cook, "leverage" = model3.diag$h) %>%
  pivot_longer(everything(), names_to = "measure") %>%
  mutate(cutoff = ifelse(measure=="cooks",1,26/240)) %>%
  ggplot(aes(x = seq(0.5,240,by=0.5))) +
  geom_line(aes(y = value, col = measure)) +
  geom_line(aes(y = cutoff), lty = 2, alpha = 0.5) +
  theme_classic() +
  facet_wrap(~measure, scales = "free_y", nrow = 2) +
  scale_color_manual(values = c("orange","cornflowerblue")) +
  labs(x = "observation")
```

```{r}
p_res3 <- residuals(model3, type = "pearson")
d_res3 <- residuals(model3, type = "deviance")
data.frame("pearson" = p_res3, "deviance" = d_res3) %>%
  pivot_longer(everything(), names_to = "residual") %>%
  ggplot(aes(x = seq(0.5,240,by=0.5), y = value, col = residual)) +
  geom_point() +
  facet_wrap(~residual, nrow = 2) +
  theme_classic() +
  scale_color_manual(values = c("darkgreen","purple")) +
  labs(x = "observation")
data.frame("pearson" = model3.diag$rp, "deviance" = model3.diag$rd) %>%
  pivot_longer(everything(), names_to = "residual") %>%
  ggplot(aes(x = seq(0.5,240,by=0.5), y = value, col = residual)) +
  geom_point() +
  facet_wrap(~residual, nrow = 2) +
  theme_classic() +
  scale_color_manual(values = c("darkgoldenrod2","orchid3")) +
  labs(x = "observation", y = "standardized values")
#kable(data.frame("pearson" = p_res3, "deviance" = d_res3,"leverage" = model3.diag$h, "cooks" = model3.diag$cook,"p_standard" = model3.diag$rp, "d_standard" = model3.diag$rd),col.names = c("$\\hat{r}^{P}$","$\\hat{r}^{D}$","leverage","cooks","$\\hat{r}^{PS}$","$\\hat{r}^{DS}$"))
```
```{r}
library(VGAM)
# model 5: proportional odds model
dd1$CD86 = data$CD86
dd1$DDX58 = data$DDX58
dd1$KLRD1 = data$KLRD1
dd1$TLR4 = data$TLR4
dd1$pathStage = as.factor(data$stage)
model5 <- vglm(pathStage ~ MC1R + AKT1 + PAK2 + SOS1 + B2M + sex + age_c + CD86 + DDX58 + KLRD1 + TLR4, data = dd1, family = cumulative(parallel=T))
summary(model5)
```

```{r}
model6 <- vglm(pathStage ~ MC1R + AKT1 + PAK2 + SOS1 + B2M + sex + age_c + CD86 + DDX58 + KLRD1 + TLR4
                + age_c:CD86 + age_c:DDX58 + age_c:KLRD1 + age_c:TLR4 , data = dd1, family = cumulative(parallel = T))
summary(model6)
```


