---
title: "Proj651"
author: "Group 7"
date: "2022/4/11"
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

```{r}
library(tidyverse)
library(gtable)
library(gtsummary)
library(gridExtra)
library(knitr)
library(car)
library(boot)

data <- readRDS("Dataset.RData") %>%
  mutate(age_c = mean(age)-age,
         trans_class_bin = ifelse(trans_class == "immune",1,0),
         prop_infiltrated = infiltration_count/tile_count,
         stage_bin = ifelse(stage == 3, "3",
                            ifelse(stage == 4, NA, "1-2")),
         sex = as.factor(gender),
         pathStage = as.factor(stage_bin),
         survival = factor(survival, levels = c("Short","Long"))) %>%
  filter(!is.na(stage_bin) & !is.na(survival))

N = length(data$id)
```

```{r}
# immune selected genes MC1R, AKT1, NAMPT, TNFRSF19, PAK2, SOS1, B2M 
l1 <- glm(survival ~ MC1R + as.factor(stage), data = data, family = 'binomial')
l2 <- glm(survival ~ AKT1 + as.factor(stage), data = data, family = 'binomial')
l3 <- glm(survival ~ NAMPT + as.factor(stage), data = data, family = 'binomial')
l4 <- glm(survival ~ TNFRSF19 + as.factor(stage), data = data, family = 'binomial')
l5 <- glm(survival ~ PAK2 + as.factor(stage), data = data, family = 'binomial')
l6 <- glm(survival ~ SOS1 + as.factor(stage), data = data, family = 'binomial')
l7 <- glm(survival ~ B2M + as.factor(stage), data = data, family = 'binomial')

betas <- c(l1$coefficients[2], l2$coefficients[2], l3$coefficients[2], l4$coefficients[2], l5$coefficients[2], l6$coefficients[2], l7$coefficients[2])

betas %>%
  kable(col.names = "$\\hat{\\beta}$")
```

```{r}
dd = data[c('MC1R', 'AKT1', 'NAMPT', 'TNFRSF19', 'PAK2', 'SOS1', 'B2M')] 
library(plotly)
library(ggcorrplot)
library(heatmaply)
heatmaply_cor(cor(dd))
```

```{r}
cor(dd)
```

```{r}
model = glm(survival ~ MC1R + AKT1 + NAMPT + TNFRSF19 + PAK2 + SOS1 + B2M + pathStage, data = data, family = 'binomial')
data.frame(names(vif(model)[-8]), unname(vif(model)[-8]), unname(betas)) %>%
  kable(col.names = c("Gene","VIF","$\\hat{\\beta}$"))
```

```{r}
# selected top genes: MC1R, AKT1, PAK2, SOS1, B2M
# model 1: basline + selected top genes

model1 <- glm(survival ~ MC1R + AKT1 + PAK2 + sex + age_c + pathStage, data = data, family = 'binomial')
summary(model1)

gtsummary::tbl_regression(model1) %>%
  bold_p()
```

```{r residual diagnostics}
lev1 <- (length(coefficients(model1))*2+2)/N
model1.diag <- glm.diag(model1)
data.frame("cooks" = model1.diag$cook, "leverage" = model1.diag$h) %>%
  pivot_longer(everything(), names_to = "measure") %>%
  mutate(cutoff = ifelse(measure=="cooks",4/N,lev1)) %>%
  ggplot(aes(x = seq(0.5,N,by=0.5))) +
  geom_line(aes(y = value, col = measure)) +
  geom_line(aes(y = cutoff), lty = 2, alpha = 0.5) +
  theme_classic() +
  facet_wrap(~measure, scales = "free_y", nrow = 2) +
  scale_color_manual(values = c("orange","cornflowerblue")) +
  labs(x = "observation")
```

```{r }
p_res1 <- residuals(model1, type = "pearson")
d_res1 <- residuals(model1, type = "deviance")
data.frame("pearson" = p_res1, "deviance" = d_res1) %>%
  pivot_longer(everything(), names_to = "residual") %>%
  ggplot(aes(x = seq(0.5,N,by=0.5), y = value, col = residual)) +
  geom_point() +
  facet_wrap(~residual, nrow = 2) +
  theme_classic() +
  scale_color_manual(values = c("darkgreen","purple")) +
  labs(x = "observation")
data.frame("pearson" = model1.diag$rp, "deviance" = model1.diag$rd) %>%
  pivot_longer(everything(), names_to = "residual") %>%
  ggplot(aes(x = seq(0.5,N,by=0.5), y = value, col = residual)) +
  geom_point() +
  facet_wrap(~residual, nrow = 2) +
  theme_classic() +
  scale_color_manual(values = c("darkgreen","purple")) +
  labs(x = "observation", y = "standardized values")
#kable(data.frame("pearson" = p_res1, "deviance" = d_res1,"leverage" = model1.diag$h, "cooks" = model1.diag$cook,"p_standard" = model1.diag$rp, "d_standard" = model1.diag$rd),col.names = c("$\\hat{r}^{P}$","$\\hat{r}^{D}$","leverage","cooks","$\\hat{r}^{PS}$","$\\hat{r}^{DS}$"))
```


```{r}
# model 2: baseline + selected top genes + immune response genes

model2 <- glm(survival ~ MC1R + AKT1 + PAK2 + sex + age_c + DDX58 + KLRD1 + TLR4 + pathStage, data = data, family = 'binomial')
summary(model2)
```


```{r}
lev2 = (length(coefficients(model2))*2+2)/N
model2.diag <- glm.diag(model2)
data.frame("cooks" = model2.diag$cook, "leverage" = model2.diag$h) %>%
  pivot_longer(everything(), names_to = "measure") %>%
  mutate(cutoff = ifelse(measure=="cooks",4/N,lev2)) %>%
  ggplot(aes(x = seq(0.5,N,by=0.5))) +
  geom_line(aes(y = value, col = measure)) +
  geom_line(aes(y = cutoff), lty = 2, alpha = 0.5) +
  theme_classic() +
  facet_wrap(~measure, scales = "free_y", nrow = 2) +
  scale_color_manual(values = c("orange","cornflowerblue")) +
  labs(x = "observation")
```

```{r}
p_res2 <- residuals(model2, type = "pearson")
d_res2 <- residuals(model2, type = "deviance")
data.frame("pearson" = p_res2, "deviance" = d_res2) %>%
  pivot_longer(everything(), names_to = "residual") %>%
  ggplot(aes(x = seq(0.5,N,by=0.5), y = value, col = residual)) +
  geom_point() +
  facet_wrap(~residual, nrow = 2) +
  theme_classic() +
  scale_color_manual(values = c("darkgreen","purple")) +
  labs(x = "observation")
data.frame("pearson" = model2.diag$rp, "deviance" = model2.diag$rd) %>%
  pivot_longer(everything(), names_to = "residual") %>%
  ggplot(aes(x = seq(0.5,N,by=0.5), y = value, col = residual)) +
  geom_point() +
  facet_wrap(~residual, nrow = 2) +
  theme_classic() +
  scale_color_manual(values = c("darkgoldenrod2","orchid3")) +
  labs(x = "observation", y = "standardized values")
#kable(data.frame("pearson" = p_res2, "deviance" = d_res2,"leverage" = model2.diag$h, "cooks" = model2.diag$cook,"p_standard" = model2.diag$rp, "d_standard" = model2.diag$rd),col.names = c("$\\hat{r}^{P}$","$\\hat{r}^{D}$","leverage","cooks","$\\hat{r}^{PS}$","$\\hat{r}^{DS}$"))
```

```{r NEW interaction model}
# model 3: baseline + selected top genes (2!!!) + immune response genes + age:immune response genes
model3 <- glm(survival ~ pathStage*MC1R + pathStage*AKT1 + pathStage*PAK2 + sex + age_c, data = data, family = 'binomial')

model4 <- glm(survival ~ pathStage*MC1R + pathStage*AKT1 + pathStage*PAK2 + sex + age_c + pathStage*DDX58 + pathStage*KLRD1 + pathStage*TLR4, data = data, family = 'binomial')

gtsummary::tbl_regression(model3)
gtsummary::tbl_regression(model4)

anova(model3, model4, test = "LRT")
anova(model1, model2, test = "LRT")
```

```{r}
lev3 = (2*length(coefficients(model3))+2)/N
model3.diag <- glm.diag(model3)
data.frame("Cooks" = model3.diag$cook, "Leverage" = model3.diag$h) %>%
  pivot_longer(everything(), names_to = "Measure") %>%
  mutate(cutoff = ifelse(Measure=="Cooks",4/N,lev3)) %>%
  ggplot(aes(x = seq(0.5,N,by=0.5))) +
  geom_line(aes(y = value, col = Measure)) +
  geom_line(aes(y = cutoff), lty = 2, alpha = 0.5) +
  theme_classic() +
  facet_wrap(~Measure, scales = "free_y", nrow = 2) +
  scale_color_manual(values = c("orange","cornflowerblue")) +
  labs(x = "observation")

lev4 = (2*length(coefficients(model4))+2)/N

model4.diag <- glm.diag(model4)
data.frame("Cooks" = model4.diag$cook, "Leverage" = model4.diag$h) %>%
  pivot_longer(everything(), names_to = "Measure") %>%
  mutate(cutoff = ifelse(Measure=="Cooks",4/N,lev4)) %>%
  ggplot(aes(x = seq(0.5,N,by=0.5))) +
  geom_line(aes(y = value, col = Measure)) +
  geom_line(aes(y = cutoff), lty = 2, alpha = 0.5) +
  theme_classic() +
  theme(text = element_text(size = 16)) +
  facet_wrap(~Measure, scales = "free_y", nrow = 2) +
  scale_color_manual(values = c("orange","cornflowerblue")) +
  labs(x = "Observation", y = "Value")

data.frame(cook = model4.diag$cook) %>%
  ggplot(aes(x = 1:N, y = cook)) +
  geom_hline(aes(yintercept = 4/N), col = "gray20", lty = 2) +
  geom_line(col = "navy", size = 1) +
  theme_classic() +
  theme(text = element_text(size = 18)) +
  labs(y = "Cook's Distance", x = "Observation")


data[c(66,146,151,191),]

#ggsave("cooks_mod4.png", width = 10, height = 5)
```

```{r}
p_res3 <- residuals(model3, type = "pearson")
d_res3 <- residuals(model3, type = "deviance")
data.frame("pearson" = p_res3, "deviance" = d_res3) %>%
  pivot_longer(everything(), names_to = "residual") %>%
  ggplot(aes(x = seq(0.5,N,by=0.5), y = value, col = residual)) +
  geom_point() +
  facet_wrap(~residual, nrow = 2) +
  theme_classic() +
  scale_color_manual(values = c("darkgreen","purple")) +
  labs(x = "observation")
data.frame("pearson" = model3.diag$rp, "deviance" = model3.diag$rd) %>%
  pivot_longer(everything(), names_to = "residual") %>%
  ggplot(aes(x = seq(0.5,N,by=0.5), y = value, col = residual)) +
  geom_point() +
  facet_wrap(~residual, nrow = 2) +
  theme_classic() +
  scale_color_manual(values = c("darkgoldenrod2","orchid3")) +
  labs(x = "observation", y = "standardized values")

p_res4 <- residuals(model4, type = "pearson")
d_res4 <- residuals(model4, type = "deviance")
data.frame("pearson" = p_res4, "deviance" = d_res4) %>%
  pivot_longer(everything(), names_to = "residual") %>%
  ggplot(aes(x = seq(0.5,N,by=0.5), y = value, col = residual)) +
  geom_point() +
  facet_wrap(~residual, nrow = 2) +
  theme_classic() +
  scale_color_manual(values = c("darkgreen","purple")) +
  labs(x = "observation")
data.frame("Pearson" = model4.diag$rp, "Deviance" = model4.diag$rd) %>%
  pivot_longer(everything(), names_to = "Residual") %>%
  ggplot(aes(x = seq(0.5,N,by=0.5), y = value, col = Residual)) +
  geom_point() +
  facet_wrap(~Residual, nrow = 2) +
  theme_classic() +
  theme(text = element_text(size = 16)) +
  scale_color_manual(values = c("darkgoldenrod2","navy")) +
  labs(x = "Observation", y = "Standardized Residuals")


data.frame("Residual" = model4.diag$rp) %>%
  ggplot(aes(x = 1:N, y = Residual)) +
  geom_point(col = "navy") +
  theme_classic() +
  theme(text = element_text(size = 18)) +
  labs(x = "Observation", y = "Standardized Residuals")

ggsave("stdres_mod4.png", width = 10, height = 5)
```

```{r NO}
library(VGAM)
# model 5: proportional odds model
model5 <- vglm(pathStage ~ MC1R + AKT1 + PAK2 + SOS1 + B2M + sex + age_c + CD86 + DDX58 + KLRD1 + TLR4, data = data, family = cumulative(parallel=T))
summary(model5)
```

```{r NO}
model6 <- vglm(pathStage ~ MC1R + AKT1 + PAK2 + SOS1 + B2M + sex + age_c + CD86 + DDX58 + KLRD1 + TLR4
                + age_c:CD86 + age_c:DDX58 + age_c:KLRD1 + age_c:TLR4 , data = data, family = cumulative(parallel = T))
summary(model6)
```


