---
title: "Final project"
author: "Annie Cohen"
date: "3/26/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
library(tidyverse)
library(gtable)
library(gtsummary)
library(gridExtra)
library(knitr)

data <- readRDS("Dataset.RData")
```

```{r}
cancerdata <- data %>%
  mutate(prop_infiltrated = infiltration_count/tile_count)

long_data <- cancerdata %>%
  pivot_longer(-colnames(cancerdata[,c(1:8,34)]), names_to = "gene", values_to = "exp")

genes <- c("TLR4","CIITA","KLRD1","MC3R","NAMPT")

## prop infiltrated ~ gene expression * gender

long_data %>%
  filter(gene %in% genes) %>%
  ggplot(aes(x = exp, y = prop_infiltrated, col = gender)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = 'lm', formula = 'y~x', se = FALSE) +
  facet_wrap(~gene) +
  scale_color_manual(values = c("cornflowerblue","darkgoldenrod2")) +
  theme_classic()

## survival ~ gene expression

long_data %>%
  filter(gene %in% genes & !is.na(survival)) %>%
  ggplot(aes(x = exp, y = survival)) +
  geom_boxplot() +
  facet_wrap(~gene, scales = "free_x") +
  theme_classic()


## stage ~ gene expression

long_data %>%
  filter(gene %in% genes & !is.na(stage)) %>%
  ggplot(aes(x = exp, y = stage)) +
  geom_boxplot(aes(group = stage)) +
  facet_wrap(~gene, scales = "free_x") +
  theme_classic()
```

```{r}
## tbl_summary object

cancerdata %>%
  tbl_summary(include = -id, by = survival) %>%
  add_p() %>%
  bold_labels() %>%
  add_overall() %>%
  bold_p()

colSums(is.na(cancerdata)) %>%
  kable()
```
