---
title: "Intermodel Comparisions"
author: "Nicolas Gargurevich"
date: "4/13/2022"
output: pdf_document
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(lmtest)
library(ResourceSelection)
library(glmtoolbox)
```

```{r,echo=FALSE}
melanoma <- readRDS("Dataset.RData") %>%
  mutate(age_c = mean(age)-age,
         trans_class_bin = ifelse(trans_class == "immune",1,0),
         prop_infiltrated = infiltration_count/tile_count)

```

## Models

```{r, echo=FALSE}
model1 <- glm(prop_infiltrated ~ KLRD1 + RFX5 + DDX58 + EIF2AK2 + CCL28 + CD86 + 
                C5 + DCK + age_c + gender + stage + trans_class_bin, 
              data = melanoma, 
              weights = tile_count, 
              family = binomial(link=logit)) 
summary(model1)

model2 <- glm(prop_infiltrated ~ KLRD1 + RFX5 + DDX58 + EIF2AK2 + CCL28 + CD86 + 
                C5 + DCK + IL17RB + TLR4 + CCL28 + IL17C + age_c + gender + 
                stage + trans_class_bin, 
              data = melanoma, 
              weights = tile_count, 
              family = binomial(link=logit)) 
summary(model2)
```

## LRTs

```{r, echo=FALSE}
lrtest(model2, model1)
```

## Deviances

```{r, echo=FALSE}
deviance(model1)
deviance(model2)
```

## Hosmer-Lemeshow 

```{r, echo=FALSE}
hoslem.test(melanoma$prop_infiltrated, fitted(model1), g=10)
hltest(model1, g=10)
hoslem.test(melanoma$prop_infiltrated, fitted(model2), g=10)
hltest(model2, g=10)
```



